export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const SET_SPINNER_MESSAGE = 'SET_SPINNER_MESSAGE';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_GROUP_CATEGORY = 'SET_GROUP_CATEGORY';
export const SET_SUB_CATEGORY = 'SET_SUB_CATEGORY';
export const SET_SIZE_CATEGORY = 'SET_SIZE_CATEGORY';
export const SET_PRODUCTS_ACCO_SIZE_AND_CATEGORY =
  'SET_PRODUCTS_ACCO_SIZE_AND_CATEGORY';
export const SET_SUB_PRODUCTS_ACCO_PRODUCT_GROUP =
  'SET_SUB_PRODUCTS_ACCO_PRODUCT_GROUP';
export const SET_CATALOG = 'SET_CATALOG';
export const SET_CATALOG_DETAILS = 'SET_CATALOG_DETAILS';
export const SET_CATALOG_IMAGES = 'SET_CATALOG_IMAGES';
